<?php
namespace eduardocasas\ColorGenerator\generator_pattern;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-27 at 13:33:55.
 */
class AbstractGeneratorPatternTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractGeneratorPattern
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('eduardocasas\ColorGenerator\generator_pattern\AbstractGeneratorPattern');
        $this->object->expects($this->any())
             ->method('generate')
             ->will($this->returnValue(array(mt_rand(0, 255), mt_rand(0, 255), mt_rand(0, 255 ))));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers eduardocasas\ColorGenerator\generator_pattern\AbstractGeneratorPattern::create
     */
    public function testCreate()
    {
        $collecton = $this->object->create();
        $this->assertArrayHasKey('r', $collecton);
        $this->assertArrayHasKey('g', $collecton);
        $this->assertArrayHasKey('b', $collecton);
    }

}
